sudo: false
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - gcc-7
      - cmake
      - ccache

script:
  - sh build.sh && cd build && make
cache:
  - ccache
  - apt
  -
    directories:
      - $HOME/.hunter

